### ISSUE TITLE
refactor: use `pkg` directory for internal libraries

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/uupd#11]

**Comment by gerblesh** [comment]
does this mean replacing `lib` folder with `pkg`?

**Comment by tulilirockz** [comment]
I believe so! As far as I know, thats the pattern people use on go. It would be nice to make the code more separated so that we can re-use it in other places like on other projects or whatever else. It also makes the code a bit cleaner since each "file" (more like module?) we have on `lib/` would be separated with its own namespace

**Comment by gerblesh** [comment]
Would we also merge `drv` into `pkg` or?

**Comment by tulilirockz** [comment]
We could but I think that wouldnt be necessary since those are quite intrinsic to this program's functionality, there wouldn't be too much sense in migrating them to make them work on a separate namespace or something. But ofc we could make it work if we wanted to
