### ISSUE TITLE
feat: handle config files

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/uupd#26]
that way we can disable/enable modules, themes, and whatsoever directly from the config

**Comment by tulilirockz** [comment]
Viper would be the best way to handle this I think.

**Comment by gerblesh** [comment]
Not sure how I feel about adding a config file, the idea was that we don't include an outside configuration file to add modules or disable them

**Comment by tulilirockz** [comment]
I believe we can do the same stuff as a config file could with just the CLI arguments, closing this
