### ISSUE TITLE
feat: sysupd support

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/uupd#38]
Would most likely be nice to support considering sysexts will be a bigger thing in a bit! I'm thinking Bazzite or Bluefin for example could have a mesa sysext or something that could be auto updated through this.

**Comment by Zeglius** [comment]
With sysupd, you mean this? 
https://www.freedesktop.org/software/systemd/man/latest/systemd-sysupdate.html

I think would be better to wait/focus for bootc sysext frontend, or at least to know how extensions are supposed to be built/distributed. That or at least the format these should follow.

**Comment by gerblesh** [comment]
We will likely follow the upstream bootc sysext implementation, closing this as "not planned" because sysext support for bootc/dnf5 will likely be coming in the future. If that needs extra support from `uupd` a separate issue should probably be created.
