### ISSUE TITLE
We need to add graceful fallbacks if stuff breaks

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/uupd#43]
I was testing uupd on Achillobator and a bad ISO completely borked uupd because brew and distrobox containers werent being found by uupd, yet still their steps were being executed instead of just disabiling the module.

**Comment by gerblesh** [comment]
this should be solved for brew, idk about distrobox and the rest.

**Comment by gerblesh** [comment]
closed by: https://github.com/ublue-os/uupd/pull/45
